[target]
programs=uni_plot
# unitdir=./utils

[compiler]
#unitdir=/home/xhermit/fpcupdeluxe/fv_utf8
#unitdir=/home/xhermit/fpcupdeluxe/fv_unicode
unitdir=./utils
#unitdir=/home/xhermit/fpcupdeluxe/fpc/units
#unitdir=../../rtl-console/src/unix
#unitdir=../../rtl-unicode/src/inc
#unitdir=../../rtl-extra/src/inc
#includedir=../../rtl-console/src/inc
# includedir=./unilib/include
# unitdir=/etc/alternatives/fp-utils/units/x86_64-linux/
#unitdir=/home/xhermit/fpcupdeluxe/fpc/units/x86_64-linux

[install]
fpcpackage=y

[default]
fpcdir=/home/xhermit/fpcupdeluxe/fpcsrc

#[prerules]
#RTL=..
#INC=$(RTL)/inc
#COMMON=$(RTL)/common
#PROCINC=$(RTL)/$(ARCH)
#UNIXINC=$(RTL)/unix
#OSPROCINC=$(RTL)/linux/$(CPU_TARGET)
#LINUXINC=$(RTL)/linux
